# Generated by Django 3.2.4 on 2023-05-24 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gascom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('num', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('phonenum', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Deliery_staff',
            fields=[
                ('num', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('phonenum', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Gas_category',
            fields=[
                ('num', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=20)),
                ('storage', models.IntegerField()),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('num', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('phonenum', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Gas_out',
            fields=[
                ('num', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('per_price', models.IntegerField()),
                ('category_num', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gascom.gas_category')),
                ('customer_num', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gascom.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Gas_in',
            fields=[
                ('num', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('per_price', models.IntegerField()),
                ('category_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gascom.gas_category')),
                ('supplier_num', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gascom.supplier')),
            ],
        ),
    ]
