# Generated by Django 3.2.4 on 2023-05-28 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gascom', '0003_rename_category_name_gas_in_category_num'),
    ]

    operations = [
         migrations.RemoveField(
            model_name='gas_out',
            name='customer_num',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='num',
        ),
       
        migrations.AlterField(
            model_name='customer',
            name='phonenum',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
