# Generated by Django 3.2.4 on 2023-05-28 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gascom', '0004_auto_20230528_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='gas_out',
            name='customer_pho',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gascom.customer'),
        ),
    ]
