# Generated by Django 3.2.4 on 2023-05-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gascom', '0005_gas_out_customer_pho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gas_out',
            name='num',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
