# Generated by Django 3.2.4 on 2023-05-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gascom', '0006_alter_gas_out_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='gas_out',
            name='is_deliery',
            field=models.IntegerField(default=0),
        ),
    ]
