# Generated by Django 3.2.4 on 2023-06-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gascom', '0008_deliery_gas'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='money',
            field=models.IntegerField(default=0),
        ),
    ]
